### ISSUE TITLE
Not working properly after Caddy2

### ISSUE THREAD

**Issue by wsndshx** [librespeed/speedtest-go#14]
## Description
I use Caddy2 to forward access on port 443 to port 8989. I can open the page but cannot perform speed testing.

## Server
URL: https://speedtest.fishfish.date/

###Caddy Config
```
speedtest.fishfish.date {
    encode gzip
    root * /speedtest-go/assets
    file_server
    reverse_proxy / localhost:8989 {
        header_up -Origin
    }
}
```

###speedtest settings
speedtest settings are the default

## Client
Browser: Chrome 86.0.4240.183,
OS: Window 10

## Steps to reproduce
* Click to start.
* Unable to measure download speed.

## Expected behaviour
The file should be downloaded from the server and the speed measured.

## Screenshots
<img width="971" alt="Snipaste_2020-11-05_22-44-08" src="https://user-images.githubusercontent.com/7829265/98255534-75755780-1fb8-11eb-92b6-9e3c85cdc75e.png">

**Comment by maddie** [comment]
I'm not sure about Caddy's configuration, maybe try to remove the `root * /speedtest-go/assets` line? And what does the `fileserver` line do?

The `assets` should be served by the Go backend instead of Caddy, so can just forward all requests to the backend.

**Comment by wsndshx** [comment]
> I'm not sure about Caddy's configuration, maybe try to remove the `root * /speedtest-go/assets` line? And what does the `file_server` line do?
> 
> The `assets` should be served by the Go backend instead of Caddy, so can just forward all requests to the backend.

`root * /speedtest-go/assets` and `file_server` are used to indicate the root directory of the site and allow it to access static files (js). After deleting them, the website seems to become a static page with no response.

This seems to be a problem with caddy's handling of URLs. I will try other reverse proxy solutions.

**Comment by maddie** [comment]
Here's an [Nginx configuration](https://github.com/librespeed/speedtest/wiki/Installation-(Go)#reverse-proxy-nginx-etc) FYR.

**Comment by wsndshx** [comment]
> 这是[Nginx配置的](https://github.com/librespeed/speedtest/wiki/Installation-(Go)#reverse-proxy-nginx-etc)FYR。

I found out that my configuration file was wrong.(orz)

I modified the configuration file to the following so that it can run normally.

```
speedtest.example.com {
    encode gzip
    reverse_proxy localhost:8989
}
```
