### ISSUE TITLE
running server without db and telemetry support

### ISSUE THREAD

**Issue by blnprasad** [librespeed/speedtest-go#21]
I want to use server in cli mode alone by disabling DB & telemetry support. I went through the code and got some hacky steps but it would be great if you can provide the steps needed for same.

**Comment by maddie** [comment]
Currently, the result PNG output depends on database storage. Implementing this change would require some refactoring, and possibly not compatible with PHP version frontends.

**Comment by O-Luhishi** [comment]
Are there any updates on this? I'm looking at trying to use this just for a HTML frontend to consume without DB & Telemetry but facing the same issue, the code is relatively hacky. PNG output doesn't seem to be a dealbreaker.
