### ISSUE TITLE
Bump Release

### ISSUE THREAD

**Issue by cheriimoya** [librespeed/speedtest-go#22]
## Description
It would be great if someone could bump the release number to 1.1.3 with the current master.

## Why it should be implemented
From a user perspective, the previous commits changed the UI a lot, since the rendered PNG looks quite different (at least to me) and i really like the added timestamp on the lower left @maddie .
Would be great if you could bump the tag:)

**Comment by mickkael** [comment]
Once done, I'll publish the container with this tag 
https://hub.docker.com/r/mickkael/librespeed-go/tags?page=1&ordering=last_updated

**Comment by maddie** [comment]
v1.1.3 is released.
