### ISSUE TITLE
Pagetitle appears as zzz.cat 'Speedtest'

### ISSUE THREAD

**Issue by fitchtravis** [librespeed/speedtest-go#32]
## Description
Hosting this internally, the page title appears as 'zzz.cat Speedtest'

## Server
the  function setPageTitle() in index.html is not correctly returning the location.hostname and results in a page title of 

zzz.cat Speedtest

**Comment by maddie** [comment]
You should probably provide your own page using `assets` directory, but I'll change the pages back to default ones for now
