### ISSUE TITLE
Can you support letsencrypt

### ISSUE THREAD

**Issue by larvacent** [librespeed/speedtest-go#4]
## Description
If I have multiple servers, I only need to specify the domain name in the configuration file to automatically support SSL, just like the speedtest.net server.

**Comment by xiruizhao** [comment]
You should use nginx to reverse proxy this server and set X-Real-IP header.

**Comment by maddie** [comment]
The recommended way would be using Nginx or the likes as a reverse proxy with SSL termination. Built-in SSL cert management is not considered for now, sorry.
