### ISSUE TITLE
Why is the new version not released? Was the last released version last year?

### ISSUE THREAD

**Issue by masx200** [librespeed/speedtest-go#46]
## Description
A short description of your idea
Why is the new version not released? Was the last released version last year?
## Why it should be implemented
Who it would benefit, ...
Can you release a new version with an executable file with Windows?
https://github.com/librespeed/speedtest-go/issues/44#event-6961598968
https://github.com/librespeed/speedtest-go/pull/45#event-6961599000
## Optional: implementation suggestions
If you have experience in this field, feel free to give us suggestions

## Optional: screenshots
Add some screenshots, mockups, ... if they help clarify what you want

**Comment by maddie** [comment]
It's just released. What's the problem here?
