### ISSUE TITLE
Support Proxy Protocol

### ISSUE THREAD

**Issue by mildis** [librespeed/speedtest-go#9]
ProxyProtocol is a light and fast way for an upstream reverse-proxy to talk to its downstream servers.  
Plus, it properly adds client IP address.  
Supporting ProxyProtocol could provide more accurate results and less error in the client IP address detection.

A GO implementation is available at https://github.com/pires/go-proxyproto

**Comment by maddie** [comment]
Can you provide a use-case for implementing proxy protocol in the backend? Which frontend is going to be sending the proxy protocol headers?

**Comment by mildis** [comment]
We are using haproxy, whose author is also the Proxy Protocol author.  
AWS Network Load Balancer sends ProxyProtocol : users running librespeed-go backend in AWS would benefit this.

**Comment by maddie** [comment]
Implemented. Thanks for your suggestion.

**Comment by maddie** [comment]
Released under tag v1.1.0
